name: Build and test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        java-version: ['8', '11']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew build
      - name: Upload test report
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-report-${{ matrix.java-version }}
          path: build/reports/tests/**/*.html